"use client"

import type React from "react"

import { createContext, useContext, useEffect, useMemo, useState } from "react"

type Lang = "fr" | "en"
type Ctx = {
  lang: Lang
  setLang: (l: Lang) => void
  t: (k: string, fallback?: string) => string
  language: Lang
  setLanguage: (l: Lang) => void
}
const LanguageCtx = createContext<Ctx | null>(null)

const dictionary: Record<Lang, Record<string, string>> = {
  fr: {
    // Navigation
    "nav.courses": "Cours",
    "nav.tests": "Tests",
    "nav.live": "Live",
    "nav.favorites": "Favoris",
    "nav.notifications": "Notifications",
    "nav.achievements": "Réussites",
    "nav.subscription": "Abonnement",
    "nav.profile": "Profil",
    "nav.download": "Télécharger",

    // Authentication
    "auth.login": "Connexion",
    "auth.signup": "Inscription",
    "auth.welcome": "Bon retour",
    "auth.create": "Créer un compte",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.confirmPassword": "Confirmer le mot de passe",
    "auth.forgotPassword": "Mot de passe oublié ?",
    "auth.rememberMe": "Se souvenir de moi",
    "auth.noAccount": "Pas de compte ?",
    "auth.hasAccount": "Déjà un compte ?",
    "auth.signInWith": "Ou continuer avec",
    "auth.terms": "En créant un compte, vous acceptez nos",
    "auth.termsLink": "Conditions d'utilisation",
    "auth.privacy": "Politique de confidentialité",
    // Logout (added)
    "auth.logout": "Déconnexion",
    "auth.logout.inProgress": "Déconnexion...",
    "auth.logout.confirm.title": "Confirmer la déconnexion",
    "auth.logout.confirm.description": "Êtes-vous sûr de vouloir vous déconnecter ? Vous devrez vous reconnecter pour accéder à votre compte.",

    // Hero Section
    "hero.title": "Réussissez le TCF/TEF avec des parcours personnalisés.",
    "hero.subtitle": "Des exercices adaptatifs, des tests blancs et des sessions live chaque semaine.",
    "hero.primary.start": "Commencer",
    "hero.primary.continue": "Continuer",
    "hero.quick": "Essai rapide 3 min",

    // Snapshot
    "snapshot.streak": "Série",
    "snapshot.goal": "Objectif du jour",
    "snapshot.level": "Niveau",
    "snapshot.continue": "Continuer",

    // Course Explorer
    "explorer.title": "Explorer les parcours",
    "explorer.grammar": "Grammaire",
    "explorer.listening": "Compréhension orale",
    "explorer.reading": "Compréhension écrite",
    "explorer.vocab": "Vocabulaire",
    "explorer.writing": "Expression écrite",
    "explorer.oral": "Expression orale",
    "explorer.sims": "Méthodologie TCF/TEF",
    "explorer.subtitle": "Parcours guidé",

    // Tests
    "tests.title": "Tests & Entraînement",
    "tests.mock": "Commencer un test blanc",
    "tests.viewAll": "Voir tous les tests",
    "tests.duration.3": "3 min",
    "tests.duration.5": "5 min",
    "tests.duration.10": "10 min",
    "tests.duration.20": "20 min",
    "tests.duration.30": "30 min",
    "tests.filter.all": "Tous",
    "tests.filter.free": "Gratuit",
    "tests.filter.essential": "Essentiel",
    "tests.filter.premium": "Premium",
    "tests.filter.pro": "Pro+",
    "tests.tcf.simulation": "Simulation TCF/TEF",
    "tests.results": "Voir les résultats des tests",

    // Live Sessions
    "live.title": "Sessions Live Interactives",
    "live.subtitle":
      "Rejoignez nos sessions en direct animées par des experts certifiés. Apprenez, pratiquez et progressez en temps réel.",
    "live.cta": "Rejoindre maintenant",
    "live.program": "Voir le programme",
    "live.categories.all": "Toutes",
    "live.categories.free": "Gratuites",
    "live.categories.workshops": "Ateliers",
    "live.categories.exams": "Examens",
    "live.categories.conversation": "Conversation",

    // Feed
    "feed.title": "Quoi de neuf",
    "feed.like": "J'aime",
    "feed.comment": "Commenter",
    "feed.share": "Partager",
    "feed.loadMore": "Charger plus",
    "feed.writeComment": "Écrire un commentaire…",
    "feed.locked": "Contenu réservé aux abonnés — Passer en Premium",

    // Notifications
    "notif.pill": "nouvelles notifications",
    "notif.title": "Notifications",
    "notif.markAllRead": "Tout marquer comme lu",
    "notif.noNotifications": "Aucune notification",

    // Subscription & Upsell
    "upsell.title": "Passez en Premium",
    "upsell.benefits": "Avantages Premium",
    "upsell.b1": "Examens blancs complets",
    "upsell.b2": "Analyses avancées",
    "upsell.b3": "Sessions live illimitées",
    "upsell.cta": "Passer en Premium",
    "upsell.pricing": "Voir les tarifs",
    "subscription.free": "Gratuit",
    "subscription.essential": "Essentiel",
    "subscription.premium": "Premium",
    "subscription.pro": "Pro+",

    // Download Page
    "download.title": "Téléchargements",
    "download.subtitle": "Accédez à du contenu exclusif basé sur votre abonnement",
    "download.search.placeholder": "Rechercher du contenu...",
    "download.filters.category": "Catégorie",
    "download.filters.subscription": "Abonnement",
    "download.filters.all": "Tous",
    "download.filters.grammar": "Grammaire",
    "download.filters.vocabulary": "Vocabulaire",
    "download.filters.listening": "Écoute",
    "download.filters.writing": "Écriture",
    "download.filters.tests": "Tests",
    "download.subscription.current": "Abonnement Actuel",
    "download.subscription.description": "Votre niveau d'abonnement détermine le contenu accessible",
    "download.subscription.access": "Accès aux contenus gratuits et essentiels",
    "download.subscription.upgrade": "Améliorer",
    "download.button": "Télécharger",
    "download.locked": "Verrouillé",
    "download.downloads": "téléchargements",
    "download.noResults": "Aucun contenu trouvé",
    "download.noResults.description": "Essayez de modifier vos filtres de recherche",

    // Download Content
    "download.content.grammar.title": "Guide Complet de Grammaire TCF",
    "download.content.grammar.description": "Guide complet de grammaire avec exercices et exemples",
    "download.content.pronunciation.title": "Masterclass de Prononciation Française",
    "download.content.pronunciation.description": "Leçons audio pour une prononciation française parfaite",
    "download.content.mockexams.title": "Collection d'Examens Blancs TCF",
    "download.content.mockexams.description": "10 tests de pratique TCF complets avec solutions",
    "download.content.vocabulary.title": "Constructeur de Vocabulaire Français",
    "download.content.vocabulary.description": "Vocabulaire essentiel pour réussir le TCF/TEF",
    "download.content.listening.title": "Vidéos de Compréhension Orale",
    "download.content.listening.description": "Exercices vidéo pour la compréhension orale",
    "download.content.writing.title": "Modèles d'Expression Écrite",
    "download.content.writing.description": "Modèles et exemples pour l'expression écrite",

    // Free Trial Activation
    "freetrial.title": "Activez Votre Essai Gratuit",
    "freetrial.subtitle": "Débloquez l'accès premium pendant 24 heures",
    "freetrial.benefit1": "Accès à tous les cours premium",
    "freetrial.benefit2": "Tests blancs illimités",
    "freetrial.benefit3": "Sessions live exclusives",
    "freetrial.benefit4": "Analyses détaillées",
    "freetrial.activate": "Activer l'Essai Gratuit",
    "freetrial.terms": "En activant l'essai, vous acceptez nos conditions d'utilisation",

    // Profile
    "profile.title": "Profil",
    "profile.subtitle": "Gérez vos informations et suivez vos progrès",
    "profile.settings": "Paramètres",
    "profile.stats.score": "Score moyen",
    "profile.stats.streak": "Jours consécutifs",
    "profile.stats.achievements": "Réussites",
    "profile.stats.studyTime": "Temps d'étude",

    // Achievements
    "achievements.title": "Mes Réussites",
    "achievements.subtitle": "Suivez vos progrès et débloquez des certifications",
    "achievements.stats.title": "Statistiques Générales",
    "achievements.stats.tests": "Tests Complétés",
    "achievements.stats.hours": "Heures d'Étude",
    "achievements.stats.streak": "Série Actuelle",
    "achievements.stats.level": "Niveau Actuel",
    "achievements.badges.title": "Badges & Certifications",
    "achievements.progress.title": "Progression par Compétence",
    "achievements.recent.title": "Activité Récente",
    "achievements.leaderboard.title": "Classement",
    "achievements.badge.earned": "Obtenu",
    "achievements.badge.locked": "Verrouillé",

    // Admin Section - Comprehensive translations
    "admin.title": "Administration",
    "admin.dashboard": "Tableau de bord",
    "admin.users": "Utilisateurs",
    "admin.content": "Contenu",
    "admin.managers": "Managers",
    "admin.settings": "Paramètres",
    "admin.analytics": "Analyses",
    "admin.reports": "Rapports",
    "admin.feed": "Mon Feed",
    "admin.login.title": "Connexion Administrateur",
    "admin.login.subtitle": "Accédez au panneau d'administration",
    "admin.login.username": "Nom d'utilisateur",
    "admin.login.email": "Adresse email",
    "admin.login.emailPlaceholder": "admin@exemple.com",
    "admin.login.emailHint": "Utilisez l'email administrateur fourni",
    "admin.login.passwordPlaceholder": "Entrez votre mot de passe",
    "admin.login.signin": "Se connecter",
    "admin.login.success": "Connexion réussie! Bienvenue",
    "admin.stats.activeUsers": "Utilisateurs actifs",
    "admin.stats.totalCourses": "Cours disponibles",
    "admin.stats.monthlyRevenue": "Revenus mensuels",
    "admin.stats.successRate": "Taux de réussite",
    "admin.content.create": "Créer du contenu",
    "admin.content.createPost": "Créer un post",
    "admin.users.total": "Total des utilisateurs",
    "admin.users.active": "Utilisateurs actifs",
    "admin.users.premium": "Abonnés premium",
    "admin.users.manage": "Gérer les utilisateurs",
    "admin.users.filter": "Filtrer les utilisateurs",
    "admin.users.search": "Rechercher un utilisateur",
    "admin.users.export": "Exporter",
    "admin.users.import": "Importer",
    "admin.users.delete": "Supprimer l'utilisateur",
    "admin.users.edit": "Modifier l'utilisateur",
    "admin.users.view": "Voir le profil",
    "admin.users.suspend": "Suspendre",
    "admin.users.activate": "Activer",
    "admin.content.upload": "Télécharger du contenu",
    "admin.content.manage": "Gérer le contenu",
    "admin.content.moderate": "Modérer",
    "admin.content.approve": "Approuver",
    "admin.content.reject": "Rejeter",
    "admin.content.publish": "Publier",
    "admin.content.unpublish": "Dépublier",
    "admin.sessions.manage": "Gérer les sessions",
    "admin.sessions.create": "Créer une session",
    "admin.sessions.schedule": "Programmer",
    "admin.sessions.cancel": "Annuler",
    "admin.sessions.participants": "Participants",
    "admin.subscriptions.manage": "Gérer les abonnements",
    "admin.subscriptions.plans": "Plans d'abonnement",
    "admin.subscriptions.billing": "Facturation",
    "admin.subscriptions.refunds": "Remboursements",
    "admin.settings.general": "Général",
    "admin.settings.security": "Sécurité",
    "admin.settings.notifications": "Notifications",
    "admin.settings.integrations": "Intégrations",
    "admin.settings.backup": "Sauvegarde",
    "admin.settings.maintenance": "Maintenance",

    // Manager Authentication & Login
    "manager.login.title": "Connexion Manager",
    "manager.login.subtitle": "Accédez à votre espace de gestion",
    "manager.login.selectRole": "Sélectionnez votre rôle",
    "manager.login.username": "Nom d'utilisateur",
    "manager.login.email": "Adresse email",
    "manager.login.emailPlaceholder": "exemple@domaine.com",
    "manager.login.emailHint": "Utilisez l'email fourni par l'administrateur",
    "manager.login.emailRequired": "Email requis",
    "manager.login.password": "Mot de passe",
    "manager.login.passwordPlaceholder": "Entrez votre mot de passe",
    "manager.login.passwordRequired": "Mot de passe requis",
    "manager.login.roleHint": "Choisissez le rôle correspondant à vos permissions",
    "manager.login.roleNotMatching": "Votre rôle ne correspond pas à la sélection",
    "manager.login.connectionError": "Erreur de connexion. Veuillez réessayer.",
    "manager.login.signin": "Se connecter",
    "manager.login.signingin": "Connexion en cours...",
    "manager.login.rememberMe": "Se souvenir de moi",
    "manager.login.secureAccess": "Accès Sécurisé",
    "manager.login.secureDescription": "Interface réservée aux managers. Connexions surveillées et sécurisées.",
    "manager.login.selected": "Sélectionné",
    "manager.login.incorrectCredentials": "Identifiants incorrects pour ce rôle",
    "manager.login.success": "Connexion réussie! Bienvenue",

    // Manager Roles & Permissions
    "manager.role.junior": "Manager Junior",
    "manager.role.senior": "Manager Senior",
    "manager.role.content": "Manager de Contenu",
    "manager.role.junior.description": "Gestion de contenu A1-B1",
    "manager.role.senior.description": "Gestion complète A1-C2",
    "manager.role.content.description": "Gestion de contenu étendue",
    "manager.permissions.createCourses": "Créer des cours",
    "manager.permissions.createTests": "Créer des tests",
    "manager.permissions.hostSessions": "Animer des sessions",
    "manager.permissions.moderateContent": "Modérer le contenu",
    "manager.permissions.manageUsers": "Gérer les utilisateurs",
    "manager.permissions.viewAnalytics": "Voir les analyses",
    "manager.permissions.exportData": "Exporter les données",

    // Manager Dashboard
    "manager.dashboard.welcome": "Bienvenue",
    "manager.dashboard.subtitle": "Gérez vos cours, sessions et étudiants en un seul endroit",
    "manager.dashboard.quickActions": "Actions rapides",
    "manager.dashboard.recentActivity": "Activité récente",
    "manager.dashboard.upcomingSessions": "Sessions à venir",
    "manager.dashboard.topCourses": "Cours populaires",
    "manager.dashboard.performanceOverview": "Aperçu des performances",
    "manager.dashboard.createCourse": "Créer un cours",
    "manager.dashboard.scheduleSession": "Programmer une session",
    "manager.dashboard.createTest": "Créer un test",
    "manager.dashboard.viewStudents": "Voir les étudiants",

    // Manager Statistics
    "manager.stats.coursesCreated": "Cours créés",
    "manager.stats.testsCreated": "Tests créés",
    "manager.stats.liveSessions": "Sessions live",
    "manager.stats.studentsManaged": "Étudiants",
    "manager.stats.averageRating": "Note moyenne",
    "manager.stats.monthlyGrowth": "Croissance mensuelle",
    "manager.stats.activeStudents": "Étudiants actifs",
    "manager.stats.thisMonth": "ce mois",
    "manager.stats.thisWeek": "cette semaine",

    // Manager Content Management
    "manager.content.title": "Gestion du Contenu",
    "manager.content.createNew": "Créer du nouveau contenu",
    "manager.content.uploadFiles": "Télécharger des fichiers",
    "manager.content.manageExisting": "Gérer le contenu existant",
    "manager.content.categories": "Catégories",
    "manager.content.levels": "Niveaux",
    "manager.content.subscriptions": "Abonnements",
    "manager.content.status": "Statut",
    "manager.content.published": "Publié",
    "manager.content.draft": "Brouillon",
    "manager.content.pending": "En attente",
    "manager.content.archived": "Archivé",

    // Manager Sessions
    "manager.sessions.title": "Gestion des Sessions",
    "manager.sessions.upcoming": "Sessions à venir",
    "manager.sessions.past": "Sessions passées",
    "manager.sessions.create": "Créer une session",
    "manager.sessions.schedule": "Programmer",
    "manager.sessions.participants": "Participants",
    "manager.sessions.duration": "Durée",
    "manager.sessions.level": "Niveau",
    "manager.sessions.capacity": "Capacité",
    "manager.sessions.status": "Statut",
    "manager.sessions.live": "En direct",
    "manager.sessions.scheduled": "Programmée",
    "manager.sessions.completed": "Terminée",
    "manager.sessions.cancelled": "Annulée",

    // Manager Students
    "manager.students.title": "Gestion des Étudiants",
    "manager.students.active": "Étudiants actifs",
    "manager.students.total": "Total des étudiants",
    "manager.students.progress": "Progression",
    "manager.students.performance": "Performance",
    "manager.students.engagement": "Engagement",
    "manager.students.lastActivity": "Dernière activité",
    "manager.students.subscription": "Abonnement",
    "manager.students.level": "Niveau",
    "manager.students.joinDate": "Date d'inscription",

    // Manager Feed & Posts
    "manager.feed.title": "Mon Feed",
    "manager.feed.createPost": "Créer un post",
    "manager.feed.myPosts": "Mes publications",
    "manager.feed.drafts": "Brouillons",
    "manager.feed.scheduled": "Programmés",
    "manager.feed.published": "Publiés",
    "manager.feed.analytics": "Analyses",
    "manager.feed.engagement": "Engagement",
    "manager.feed.reach": "Portée",
    "manager.feed.interactions": "Interactions",
    "manager.feed.comments": "Commentaires",
    "manager.feed.likes": "J'aime",
    "manager.feed.shares": "Partages",

    // Manager Analytics
    "manager.analytics.title": "Analyses et Rapports",
    "manager.analytics.overview": "Vue d'ensemble",
    "manager.analytics.students": "Analyses des étudiants",
    "manager.analytics.content": "Performance du contenu",
    "manager.analytics.sessions": "Analyses des sessions",
    "manager.analytics.engagement": "Engagement",
    "manager.analytics.completion": "Taux de completion",
    "manager.analytics.satisfaction": "Satisfaction",
    "manager.analytics.retention": "Rétention",
    "manager.analytics.export": "Exporter les données",

    // Manager Settings
    "manager.settings.title": "Paramètres Manager",
    "manager.settings.profile": "Profil",
    "manager.settings.preferences": "Préférences",
    "manager.settings.notifications": "Notifications",
    "manager.settings.security": "Sécurité",
    "manager.settings.permissions": "Permissions",
    "manager.settings.language": "Langue",
    "manager.settings.theme": "Thème",
    "manager.settings.timezone": "Fuseau horaire",

    // Manager Navigation
    "manager.nav.dashboard": "Tableau de bord",
    "manager.nav.content": "Contenu",
    "manager.nav.sessions": "Sessions Live",
    "manager.nav.students": "Étudiants",
    "manager.nav.feed": "Mon Feed",
    "manager.nav.moderation": "Modération",
    "manager.nav.analytics": "Analytics",
    "manager.nav.createManager": "Créer Manager",
    "manager.nav.settings": "Paramètres",
    "manager.nav.logout": "Déconnexion",
    "manager.nav.search": "Rechercher dans le manager...",

    // Manager Notifications
    "manager.notifications.title": "Notifications Manager",
    "manager.notifications.new": "Nouvelles notifications",
    "manager.notifications.markRead": "Marquer comme lu",
    "manager.notifications.settings": "Paramètres de notification",
    "manager.notifications.email": "Notifications par email",
    "manager.notifications.push": "Notifications push",
    "manager.notifications.sms": "Notifications SMS",

    // Manager Moderation
    "manager.moderation.title": "Modération",
    "manager.moderation.pending": "En attente de modération",
    "manager.moderation.approved": "Approuvé",
    "manager.moderation.rejected": "Rejeté",
    "manager.moderation.flagged": "Signalé",
    "manager.moderation.review": "Réviser",
    "manager.moderation.approve": "Approuver",
    "manager.moderation.reject": "Rejeter",
    "manager.moderation.flag": "Signaler",

    // Manager Creation (Senior only)
    "manager.create.title": "Créer un Manager",
    "manager.create.selectType": "Sélectionner le type",
    "manager.create.junior": "Manager Junior",
    "manager.create.content": "Manager de Contenu",
    "manager.create.permissions": "Permissions",
    "manager.create.personalInfo": "Informations personnelles",
    "manager.create.credentials": "Identifiants",
    "manager.create.success": "Manager créé avec succès",

    // Footer
    "footer.product": "Produit",
    "footer.company": "Entreprise",
    "footer.legal": "Légal",
    "footer.courses": "Cours",
    "footer.tests": "Tests",
    "footer.live": "Live",
    "footer.subscription": "Abonnement",
    "footer.about": "À propos",
    "footer.careers": "Carrières",
    "footer.contact": "Contact",
    "footer.terms": "CGU",
    "footer.privacy": "Confidentialité",
    "footer.copyright": "© 2025 TCF-TEF — UI prototype",

    // Common
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.cancel": "Annuler",
    "common.save": "Enregistrer",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.view": "Voir",
    "common.close": "Fermer",
    "common.next": "Suivant",
    "common.previous": "Précédent",
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.sort": "Trier",
    "common.date": "Date",
    "common.time": "Heure",
    "common.duration": "Durée",
    "common.level": "Niveau",
    "common.status": "Statut",
    "common.active": "Actif",
    "common.inactive": "Inactif",
    "common.pending": "En attente",
    "common.completed": "Terminé",
    "common.yes": "Oui",
    "common.no": "Non",
  },
  en: {
    // Navigation
    "nav.courses": "Courses",
    "nav.tests": "Tests",
    "nav.live": "Live",
    "nav.favorites": "Favorites",
    "nav.notifications": "Notifications",
    "nav.achievements": "Achievements",
    "nav.subscription": "Subscription",
    "nav.profile": "Profile",
    "nav.download": "Download",

    // Authentication
    "auth.login": "Login",
    "auth.signup": "Sign up",
    "auth.welcome": "Welcome back",
    "auth.create": "Create account",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm password",
    "auth.forgotPassword": "Forgot password?",
    "auth.rememberMe": "Remember me",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.signInWith": "Or continue with",
    "auth.terms": "By creating an account, you agree to our",
    "auth.termsLink": "Terms of Service",
    "auth.privacy": "Privacy Policy",
    // Logout (added)
    "auth.logout": "Logout",
    "auth.logout.inProgress": "Logging out...",
    "auth.logout.confirm.title": "Confirm logout",
    "auth.logout.confirm.description": "Are you sure you want to log out? You will need to log back in to access your account.",

    // Hero Section
    "hero.title": "Succeed in TCF/TEF with personalized learning paths.",
    "hero.subtitle": "Adaptive exercises, full mock exams, and weekly live sessions.",
    "hero.primary.start": "Start",
    "hero.primary.continue": "Continue",
    "hero.quick": "3-minute quick try",

    // Snapshot
    "snapshot.streak": "Streak",
    "snapshot.goal": "Today's goal",
    "snapshot.level": "Level",
    "snapshot.continue": "Continue",

    // Course Explorer
    "explorer.title": "Explore paths",
    "explorer.grammar": "Grammar",
    "explorer.listening": "Listening",
    "explorer.reading": "Reading",
    "explorer.vocab": "Vocabulary",
    "explorer.writing": "Writing",
    "explorer.oral": "Oral Expression",
    "explorer.sims": "TCF/TEF Methodology",
    "explorer.subtitle": "Guided path",

    // Tests
    "tests.title": "Tests & Practice",
    "tests.mock": "Start a mock test",
    "tests.viewAll": "View all tests",
    "tests.duration.3": "3 min",
    "tests.duration.5": "5 min",
    "tests.duration.10": "10 min",
    "tests.duration.20": "20 min",
    "tests.duration.30": "30 min",
    "tests.filter.all": "All",
    "tests.filter.free": "Free",
    "tests.filter.essential": "Essential",
    "tests.filter.premium": "Premium",
    "tests.filter.pro": "Pro+",
    "tests.tcf.simulation": "TCF/TEF Simulation",
    "tests.results": "View Test Results",

    // Live Sessions
    "live.title": "Interactive Live Sessions",
    "live.subtitle": "Join our live sessions led by certified experts. Learn, practice and progress in real time.",
    "live.cta": "Join now",
    "live.program": "View program",
    "live.categories.all": "All",
    "live.categories.free": "Free",
    "live.categories.workshops": "Workshops",
    "live.categories.exams": "Exams",
    "live.categories.conversation": "Conversation",

    // Feed
    "feed.title": "What's New",
    "feed.like": "Like",
    "feed.comment": "Comment",
    "feed.share": "Share",
    "feed.loadMore": "Load more",
    "feed.writeComment": "Write a comment…",
    "feed.locked": "Subscribers-only content — Upgrade to Premium",

    // Notifications
    "notif.pill": "new notifications",
    "notif.title": "Notifications",
    "notif.markAllRead": "Mark all as read",
    "notif.noNotifications": "No notifications",

    // Subscription & Upsell
    "upsell.title": "Upgrade to Premium",
    "upsell.benefits": "Premium benefits",
    "upsell.b1": "Full mock exams",
    "upsell.b2": "Advanced analytics",
    "upsell.b3": "Unlimited live sessions",
    "upsell.cta": "Upgrade to Premium",
    "upsell.pricing": "View pricing",
    "subscription.free": "Free",
    "subscription.essential": "Essential",
    "subscription.premium": "Premium",
    "subscription.pro": "Pro+",

    // Download Page
    "download.title": "Downloads",
    "download.subtitle": "Access exclusive content based on your subscription",
    "download.search.placeholder": "Search content...",
    "download.filters.category": "Category",
    "download.filters.subscription": "Subscription",
    "download.filters.all": "All",
    "download.filters.grammar": "Grammar",
    "download.filters.vocabulary": "Vocabulary",
    "download.filters.listening": "Listening",
    "download.filters.writing": "Writing",
    "download.filters.tests": "Tests",
    "download.subscription.current": "Current Subscription",
    "download.subscription.description": "Your subscription level determines accessible content",
    "download.subscription.access": "Access to free and essential content",
    "download.subscription.upgrade": "Upgrade",
    "download.button": "Download",
    "download.locked": "Locked",
    "download.downloads": "downloads",
    "download.noResults": "No content found",
    "download.noResults.description": "Try adjusting your search filters",

    // Download Content
    "download.content.grammar.title": "TCF Grammar Complete Guide",
    "download.content.grammar.description": "Comprehensive grammar guide with exercises and examples",
    "download.content.pronunciation.title": "French Pronunciation Masterclass",
    "download.content.pronunciation.description": "Audio lessons for perfect French pronunciation",
    "download.content.mockexams.title": "TCF Mock Exam Collection",
    "download.content.mockexams.description": "10 complete TCF practice tests with solutions",
    "download.content.vocabulary.title": "French Vocabulary Builder",
    "download.content.vocabulary.description": "Essential vocabulary for TCF/TEF success",
    "download.content.listening.title": "Listening Comprehension Videos",
    "download.content.listening.description": "Video exercises for listening comprehension",
    "download.content.writing.title": "Writing Expression Templates",
    "download.content.writing.description": "Templates and examples for written expression",

    // Free Trial Activation
    "freetrial.title": "Activate Your Free Trial",
    "freetrial.subtitle": "Unlock premium access for 24 hours",
    "freetrial.benefit1": "Access to all premium courses",
    "freetrial.benefit2": "Unlimited mock tests",
    "freetrial.benefit3": "Exclusive live sessions",
    "freetrial.benefit4": "Detailed analytics",
    "freetrial.activate": "Activate Free Trial",
    "freetrial.terms": "By activating the trial, you agree to our terms of service",

    // Profile
    "profile.title": "Profile",
    "profile.subtitle": "Manage your information and track your progress",
    "profile.settings": "Settings",
    "profile.stats.score": "Average score",
    "profile.stats.streak": "Consecutive days",
    "profile.stats.achievements": "Achievements",
    "profile.stats.studyTime": "Study time",

    // Achievements
    "achievements.title": "My Achievements",
    "achievements.subtitle": "Track your progress and unlock certifications",
    "achievements.stats.title": "Overall Statistics",
    "achievements.stats.tests": "Tests Completed",
    "achievements.stats.hours": "Study Hours",
    "achievements.stats.streak": "Current Streak",
    "achievements.stats.level": "Current Level",
    "achievements.badges.title": "Badges & Certifications",
    "achievements.progress.title": "Progress by Skill",
    "achievements.recent.title": "Recent Activity",
    "achievements.leaderboard.title": "Leaderboard",
    "achievements.badge.earned": "Earned",
    "achievements.badge.locked": "Locked",

    // Admin Section - Comprehensive translations
    "admin.title": "Administration",
    "admin.dashboard": "Dashboard",
    "admin.users": "Users",
    "admin.content": "Content",
    "admin.managers": "Managers",
    "admin.settings": "Settings",
    "admin.analytics": "Analytics",
    "admin.reports": "Reports",
    "admin.feed": "My Feed",
    "admin.login.title": "Admin Login",
    "admin.login.subtitle": "Access the administration panel",
    "admin.login.username": "Username",
    "admin.login.email": "Email address",
    "admin.login.emailPlaceholder": "admin@example.com",
    "admin.login.emailHint": "Use the administrator email provided",
    "admin.login.passwordPlaceholder": "Enter your password",
    "admin.login.signin": "Sign in",
    "admin.login.success": "Login successful! Welcome",
    "admin.stats.activeUsers": "Active users",
    "admin.stats.totalCourses": "Available courses",
    "admin.stats.monthlyRevenue": "Monthly revenue",
    "admin.stats.successRate": "Success rate",
    "admin.content.create": "Create content",
    "admin.content.createPost": "Create post",
    "admin.users.total": "Total users",
    "admin.users.active": "Active users",
    "admin.users.premium": "Premium subscribers",
    "admin.users.manage": "Manage users",
    "admin.users.filter": "Filter users",
    "admin.users.search": "Search user",
    "admin.users.export": "Export",
    "admin.users.import": "Import",
    "admin.users.delete": "Delete user",
    "admin.users.edit": "Edit user",
    "admin.users.view": "View profile",
    "admin.users.suspend": "Suspend",
    "admin.users.activate": "Activate",
    "admin.content.upload": "Upload content",
    "admin.content.manage": "Manage content",
    "admin.content.moderate": "Moderate",
    "admin.content.approve": "Approve",
    "admin.content.reject": "Reject",
    "admin.content.publish": "Publish",
    "admin.content.unpublish": "Unpublish",
    "admin.sessions.manage": "Manage sessions",
    "admin.sessions.create": "Create session",
    "admin.sessions.schedule": "Schedule",
    "admin.sessions.cancel": "Cancel",
    "admin.sessions.participants": "Participants",
    "admin.subscriptions.manage": "Manage subscriptions",
    "admin.subscriptions.plans": "Subscription plans",
    "admin.subscriptions.billing": "Billing",
    "admin.subscriptions.refunds": "Refunds",
    "admin.settings.general": "General",
    "admin.settings.security": "Security",
    "admin.settings.notifications": "Notifications",
    "admin.settings.integrations": "Integrations",
    "admin.settings.backup": "Backup",
    "admin.settings.maintenance": "Maintenance",

    // Manager Authentication & Login
    "manager.login.title": "Manager Login",
    "manager.login.subtitle": "Access your management interface",
    "manager.login.selectRole": "Select your role",
    "manager.login.username": "Username",
    "manager.login.email": "Email address",
    "manager.login.emailPlaceholder": "example@domain.com",
    "manager.login.emailHint": "Use the email provided by the administrator",
    "manager.login.emailRequired": "Email required",
    "manager.login.password": "Password",
    "manager.login.passwordPlaceholder": "Enter your password",
    "manager.login.passwordRequired": "Password required",
    "manager.login.roleHint": "Choose the role corresponding to your permissions",
    "manager.login.roleNotMatching": "Your role does not match the selection",
    "manager.login.connectionError": "Connection error. Please try again.",
    "manager.login.signin": "Sign in",
    "manager.login.signingin": "Signing in...",
    "manager.login.rememberMe": "Remember me",
    "manager.login.secureAccess": "Secure Access",
    "manager.login.secureDescription": "Interface reserved for managers. Monitored and secure connections.",
    "manager.login.selected": "Selected",
    "manager.login.incorrectCredentials": "Incorrect credentials for this role",
    "manager.login.success": "Login successful! Welcome",

    // Manager Roles & Permissions
    "manager.role.junior": "Junior Manager",
    "manager.role.senior": "Senior Manager",
    "manager.role.content": "Content Manager",
    "manager.role.junior.description": "A1-B1 Content Management",
    "manager.role.senior.description": "Complete A1-C2 Management",
    "manager.role.content.description": "Extended Content Management",
    "manager.permissions.createCourses": "Create courses",
    "manager.permissions.createTests": "Create tests",
    "manager.permissions.hostSessions": "Host sessions",
    "manager.permissions.moderateContent": "Moderate content",
    "manager.permissions.manageUsers": "Manage users",
    "manager.permissions.viewAnalytics": "View analytics",
    "manager.permissions.exportData": "Export data",

    // Manager Dashboard
    "manager.dashboard.welcome": "Welcome",
    "manager.dashboard.subtitle": "Manage your courses, sessions and students in one place",
    "manager.dashboard.quickActions": "Quick actions",
    "manager.dashboard.recentActivity": "Recent activity",
    "manager.dashboard.upcomingSessions": "Upcoming sessions",
    "manager.dashboard.topCourses": "Top courses",
    "manager.dashboard.performanceOverview": "Performance overview",
    "manager.dashboard.createCourse": "Create course",
    "manager.dashboard.scheduleSession": "Schedule session",
    "manager.dashboard.createTest": "Create test",
    "manager.dashboard.viewStudents": "View students",

    // Manager Statistics
    "manager.stats.coursesCreated": "Courses created",
    "manager.stats.testsCreated": "Tests created",
    "manager.stats.liveSessions": "Live sessions",
    "manager.stats.studentsManaged": "Students",
    "manager.stats.averageRating": "Average rating",
    "manager.stats.monthlyGrowth": "Monthly growth",
    "manager.stats.activeStudents": "Active students",
    "manager.stats.thisMonth": "this month",
    "manager.stats.thisWeek": "this week",

    // Manager Content Management
    "manager.content.title": "Content Management",
    "manager.content.createNew": "Create new content",
    "manager.content.uploadFiles": "Upload files",
    "manager.content.manageExisting": "Manage existing content",
    "manager.content.categories": "Categories",
    "manager.content.levels": "Levels",
    "manager.content.subscriptions": "Subscriptions",
    "manager.content.status": "Status",
    "manager.content.published": "Published",
    "manager.content.draft": "Draft",
    "manager.content.pending": "Pending",
    "manager.content.archived": "Archived",

    // Manager Sessions
    "manager.sessions.title": "Session Management",
    "manager.sessions.upcoming": "Upcoming sessions",
    "manager.sessions.past": "Past sessions",
    "manager.sessions.create": "Create session",
    "manager.sessions.schedule": "Schedule",
    "manager.sessions.participants": "Participants",
    "manager.sessions.duration": "Duration",
    "manager.sessions.level": "Level",
    "manager.sessions.capacity": "Capacity",
    "manager.sessions.status": "Status",
    "manager.sessions.live": "Live",
    "manager.sessions.scheduled": "Scheduled",
    "manager.sessions.completed": "Completed",
    "manager.sessions.cancelled": "Cancelled",

    // Manager Students
    "manager.students.title": "Student Management",
    "manager.students.active": "Active students",
    "manager.students.total": "Total students",
    "manager.students.progress": "Progress",
    "manager.students.performance": "Performance",
    "manager.students.engagement": "Engagement",
    "manager.students.lastActivity": "Last activity",
    "manager.students.subscription": "Subscription",
    "manager.students.level": "Level",
    "manager.students.joinDate": "Join date",

    // Manager Feed & Posts
    "manager.feed.title": "My Feed",
    "manager.feed.createPost": "Create post",
    "manager.feed.myPosts": "My posts",
    "manager.feed.drafts": "Drafts",
    "manager.feed.scheduled": "Scheduled",
    "manager.feed.published": "Published",
    "manager.feed.analytics": "Analytics",
    "manager.feed.engagement": "Engagement",
    "manager.feed.reach": "Reach",
    "manager.feed.interactions": "Interactions",
    "manager.feed.comments": "Comments",
    "manager.feed.likes": "Likes",
    "manager.feed.shares": "Shares",

    // Manager Analytics
    "manager.analytics.title": "Analytics & Reports",
    "manager.analytics.overview": "Overview",
    "manager.analytics.students": "Student analytics",
    "manager.analytics.content": "Content performance",
    "manager.analytics.sessions": "Session analytics",
    "manager.analytics.engagement": "Engagement",
    "manager.analytics.completion": "Completion rate",
    "manager.analytics.satisfaction": "Satisfaction",
    "manager.analytics.retention": "Retention",
    "manager.analytics.export": "Export data",

    // Manager Settings
    "manager.settings.title": "Manager Settings",
    "manager.settings.profile": "Profile",
    "manager.settings.preferences": "Preferences",
    "manager.settings.notifications": "Notifications",
    "manager.settings.security": "Security",
    "manager.settings.permissions": "Permissions",
    "manager.settings.language": "Language",
    "manager.settings.theme": "Theme",
    "manager.settings.timezone": "Timezone",

    // Manager Navigation
    "manager.nav.dashboard": "Dashboard",
    "manager.nav.content": "Content",
    "manager.nav.sessions": "Live Sessions",
    "manager.nav.students": "Students",
    "manager.nav.feed": "My Feed",
    "manager.nav.moderation": "Moderation",
    "manager.nav.analytics": "Analytics",
    "manager.nav.createManager": "Create Manager",
    "manager.nav.settings": "Settings",
    "manager.nav.logout": "Logout",
    "manager.nav.search": "Search in manager...",

    // Manager Notifications
    "manager.notifications.title": "Manager Notifications",
    "manager.notifications.new": "New notifications",
    "manager.notifications.markRead": "Mark as read",
    "manager.notifications.settings": "Notification settings",
    "manager.notifications.email": "Email notifications",
    "manager.notifications.push": "Push notifications",
    "manager.notifications.sms": "SMS notifications",

    // Manager Moderation
    "manager.moderation.title": "Moderation",
    "manager.moderation.pending": "Pending moderation",
    "manager.moderation.approved": "Approved",
    "manager.moderation.rejected": "Rejected",
    "manager.moderation.flagged": "Flagged",
    "manager.moderation.review": "Review",
    "manager.moderation.approve": "Approve",
    "manager.moderation.reject": "Reject",
    "manager.moderation.flag": "Flag",

    // Manager Creation (Senior only)
    "manager.create.title": "Create Manager",
    "manager.create.selectType": "Select type",
    "manager.create.junior": "Junior Manager",
    "manager.create.content": "Content Manager",
    "manager.create.permissions": "Permissions",
    "manager.create.personalInfo": "Personal information",
    "manager.create.credentials": "Credentials",
    "manager.create.success": "Manager created successfully",

    // Footer
    "footer.product": "Product",
    "footer.company": "Company",
    "footer.legal": "Legal",
    "footer.courses": "Courses",
    "footer.tests": "Tests",
    "footer.live": "Live",
    "footer.subscription": "Subscription",
    "footer.about": "About",
    "footer.careers": "Careers",
    "footer.contact": "Contact",
    "footer.terms": "Terms",
    "footer.privacy": "Privacy",
    "footer.copyright": "© 2025 TCF-TEF — UI prototype",

    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.view": "View",
    "common.close": "Close",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.date": "Date",
    "common.time": "Time",
    "common.duration": "Duration",
    "common.level": "Level",
    "common.status": "Status",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.pending": "Pending",
    "common.completed": "Completed",
    "common.yes": "Yes",
    "common.no": "No",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("fr")
  useEffect(() => {
    const stored = typeof window !== "undefined" ? (localStorage.getItem("lang") as Lang | null) : null
    if (stored) setLangState(stored)
    else setLangState("fr") // Default to French if no stored preference
    if (typeof document !== "undefined") document.documentElement.lang = stored || "fr"
  }, [])
  function setLang(l: Lang) {
    setLangState(l)
    try {
      localStorage.setItem("lang", l)
      document.documentElement.lang = l
    } catch {}
  }
  const t = useMemo(() => {
    const pack = dictionary[lang]
    return (first: string, second?: string) => {
      const keyLike = /[a-z0-9_]+\.[a-z0-9_.-]+/i.test(first)
      if (second !== undefined) {
        // If first arg looks like a dictionary key and exists, use dictionary
        if (keyLike && Object.prototype.hasOwnProperty.call(pack, first)) {
          return pack[first]
        }
        // Otherwise treat as bilingual inline strings
        return lang === "fr" ? first : second
      }
      // Single-arg: assume dictionary key
      return Object.prototype.hasOwnProperty.call(pack, first) ? pack[first] : first
    }
  }, [lang])
  const value = useMemo(() => ({ lang, setLang, t, language: lang, setLanguage: setLang }), [lang])
  return <LanguageCtx.Provider value={value}>{children}</LanguageCtx.Provider>
}

export function useLang() {
  const ctx = useContext(LanguageCtx)
  if (!ctx) throw new Error("useLang must be used within LanguageProvider")
  return ctx
}

export const useLanguage = useLang
